#!/usr/bin/perl -w

$tmp_fasta = $ARGV[0];
$tmp_fasta =~ s/.fastq//g;
$tmp_fasta =~ s/.fasta//g;
$tmp_fasta .= ".fasta";
open(OUT, "> $tmp_fasta") or die"";
open(IN, $ARGV[0]) or die"Usage: perl fq_Stat.pl file.fastq\n";
while(my $line1=<IN>){
	my $line2=<IN>;
	my $line3=<IN>;
	my $line4=<IN>;
	chomp $line1;
	chomp $line2;
	chomp $line3;
	chomp $line4;
  print OUT ">$line1\n$line2\n";	
	}
close IN;
close OUT;

my $cmd = "perl /share/workplace/home/zhangxt/software/script/faSize.pl $tmp_fasta";
system($cmd);
